version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - docker.env
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - docker.env
    ports:
      - '5050:80'
    depends_on:
      - db
