version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - docker.env
    ports:
      - '8080:80'
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
