version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    networks:
      - udemy_network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      - PORT=${PORT}
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - docker.env
    ports:
      - '8080:80'
    networks:
      - udemy_network

networks:
  udemy_network:
    driver: bridge

volumes:
  postgres_data:
