import {
  MigrationInterface,
  QueryRunner,
  TableForeignKey,
  TableIndex,
} from 'typeorm';

const OLD_TABLE = 'course_set_udemy_question_banks_udemy_question_bank';
const NEW_TABLE = 'course_set_udemy_question_bank';

const OLD_COL_COURSE_SET = 'courseSetId';
const OLD_COL_QUESTION_BANK = 'udemyQuestionBankId';
const NEW_COL_COURSE_SET = 'course_set_id';
const NEW_COL_QUESTION_BANK = 'udemy_question_bank_id';

const FK_COURSE_SET = `FK_${NEW_TABLE}_${NEW_COL_COURSE_SET}`;
const FK_QUESTION_BANK = `FK_${NEW_TABLE}_${NEW_COL_QUESTION_BANK}`;
const IDX_COURSE_SET = `IDX_${NEW_TABLE}_${NEW_COL_COURSE_SET}`;
const IDX_QUESTION_BANK = `IDX_${NEW_TABLE}_${NEW_COL_QUESTION_BANK}`;

export class UpdateTableCourseSetAndUdemyQuestionBank1774272699144
  implements MigrationInterface
{
  // ─────────────────────────────────────────────────────────────────────────
  //  UP
  // ─────────────────────────────────────────────────────────────────────────
  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Guard – abort if old table does not exist
    const oldTableExists = await queryRunner.hasTable(OLD_TABLE);
    if (!oldTableExists) {
      console.warn(
        `[Migration] Table "${OLD_TABLE}" not found – migration skipped.`,
      );
      return;
    }

    // 2. Drop ALL existing foreign keys (names are auto-generated by TypeORM, so read dynamically)
    const oldTable = await queryRunner.getTable(OLD_TABLE);
    if (oldTable?.foreignKeys?.length) {
      await queryRunner.dropForeignKeys(OLD_TABLE, oldTable.foreignKeys);
    }

    // 3. Drop ALL existing indexes
    if (oldTable?.indices?.length) {
      await queryRunner.dropIndices(OLD_TABLE, oldTable.indices);
    }

    // 4. Rename the two columns
    await queryRunner.renameColumn(
      OLD_TABLE,
      OLD_COL_COURSE_SET,
      NEW_COL_COURSE_SET,
    );
    await queryRunner.renameColumn(
      OLD_TABLE,
      OLD_COL_QUESTION_BANK,
      NEW_COL_QUESTION_BANK,
    );

    // 5. Rename the table
    await queryRunner.renameTable(OLD_TABLE, NEW_TABLE);

    // 6. Recreate foreign keys with clean, predictable names
    await queryRunner.createForeignKey(
      NEW_TABLE,
      new TableForeignKey({
        name: FK_COURSE_SET,
        columnNames: [NEW_COL_COURSE_SET],
        referencedTableName: 'course_set',
        referencedColumnNames: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      }),
    );

    await queryRunner.createForeignKey(
      NEW_TABLE,
      new TableForeignKey({
        name: FK_QUESTION_BANK,
        columnNames: [NEW_COL_QUESTION_BANK],
        referencedTableName: 'udemy_question_bank',
        referencedColumnNames: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      }),
    );

    // 7. Recreate indexes
    await queryRunner.createIndex(
      NEW_TABLE,
      new TableIndex({
        name: IDX_COURSE_SET,
        columnNames: [NEW_COL_COURSE_SET],
      }),
    );

    await queryRunner.createIndex(
      NEW_TABLE,
      new TableIndex({
        name: IDX_QUESTION_BANK,
        columnNames: [NEW_COL_QUESTION_BANK],
      }),
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  //  DOWN  (full rollback)
  // ─────────────────────────────────────────────────────────────────────────
  public async down(queryRunner: QueryRunner): Promise<void> {
    // 1. Guard – abort if new table does not exist
    const newTableExists = await queryRunner.hasTable(NEW_TABLE);
    if (!newTableExists) {
      console.warn(
        `[Migration] Table "${NEW_TABLE}" not found – rollback skipped.`,
      );
      return;
    }

    // 2. Drop indexes created in up()
    const newTable = await queryRunner.getTable(NEW_TABLE);
    if (newTable?.indices?.length) {
      await queryRunner.dropIndices(NEW_TABLE, newTable.indices);
    }

    // 3. Drop foreign keys created in up()
    if (newTable?.foreignKeys?.length) {
      await queryRunner.dropForeignKeys(NEW_TABLE, newTable.foreignKeys);
    }

    // 4. Rename table back
    await queryRunner.renameTable(NEW_TABLE, OLD_TABLE);

    // 5. Rename columns back
    await queryRunner.renameColumn(
      OLD_TABLE,
      NEW_COL_QUESTION_BANK,
      OLD_COL_QUESTION_BANK,
    );
    await queryRunner.renameColumn(
      OLD_TABLE,
      NEW_COL_COURSE_SET,
      OLD_COL_COURSE_SET,
    );

    // 6. Restore original foreign keys
    await queryRunner.createForeignKey(
      OLD_TABLE,
      new TableForeignKey({
        columnNames: [OLD_COL_COURSE_SET],
        referencedTableName: 'course_set',
        referencedColumnNames: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      }),
    );

    await queryRunner.createForeignKey(
      OLD_TABLE,
      new TableForeignKey({
        columnNames: [OLD_COL_QUESTION_BANK],
        referencedTableName: 'udemy_question_bank',
        referencedColumnNames: ['id'],
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      }),
    );
  }
}
